### ISSUE TITLE
Get data dragon content

### ISSUE THREAD

**Issue by deanhaleem** [reishaleem/lol-wrapped#4]
### Description

Determine pattern for retrieving and storing content from data dragon

### TODO

- [x] Determine how and when we'll retrieve bulk data from data dragon
- [x] Determine/implement where we'll store the data
- [x] Determine/implement how we'll retrieve the data from our storage place 

### References

- https://www.communitydragon.org/

**Comment by deanhaleem** [comment]
https://riot-api-libraries.readthedocs.io/en/latest/ddragon.html

So we can make a request to get the zip file from [https://ddragon.leagueoflegends.com/cdn/dragontail-<version>.tgz](), where version is latest from [here](https://ddragon.leagueoflegends.com/api/versions.json)

**Comment by deanhaleem** [comment]
@reishaleem can you download the above and share thoughts on the best place to store data like that? I'd assume s3.

In terms of refreshing, I'm thinking every 2 weeks, staggered a little from when the patches release

**Comment by deanhaleem** [comment]
@reishaleem any thoughts?

**Comment by deanhaleem** [comment]
Spoke on zoom, going with putting everything in s3

**Comment by deanhaleem** [comment]
EventBridge and Lambda

**Comment by deanhaleem** [comment]
Every http request, make request to s3 for all assets for corresponding champions. Store in shared store, browser session storage maybe as well
